# -*- coding: utf-8 -*-
"""Deforestation Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uX3OrTsXUK35UtbbA0ocgUkYrXTJKLS5

# Deforestation Forecast
"""

# Commented out IPython magic to ensure Python compatibility.
# importing libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import re

from plotly.offline import init_notebook_mode, iplot, plot
import plotly.graph_objs as go
from plotly.subplots import make_subplots
import plotly.express as px

# %matplotlib inline

"""## Exploratory Data Analysis"""

def_amazon_data = pd.read_csv('/content/def_area_2004_2019.csv', parse_dates=True, encoding = "cp1252")
def_amazon_data.head(20)

def_amazon_data.info()

def_amazon_data.describe()

def_amazon_data.size

def_amazon_data.shape

"""## Data Preprocessing"""

#Renaming the fields for better understanding
def_amazon_data.rename({
    'ï»¿Ano/Estados':'Year',
    'AC':'Acre',
    'AM': 'Amazonas',
    'AP': 'Amapa',
    'MA':'Maranhao',
    'MT':'Mato Grosso',
    'PA':'Para',
    'RO':'Rondonia',
    'RR':'Roraima',
    'TO':'Tocantins',
    'AMZ LEGAL':'Total'
}, axis=1, inplace=True)

def_amazon_data.head()

"""## Analysis"""

fig = px.bar(def_amazon_data, x="Year", y="Total")
fig.update_layout(title_text='Total Deforested Area per Year')
fig.update_xaxes(tickmode='linear')
fig.show()

"""Here we notice that the highest amount of deforestation occured in the year 2004 but there is a slight increasing trend over the period of 2014-19"""

#Checking deforestation area by state
states=["Acre","Amazonas","Amapa","Maranhao","Mato Grosso","Para","Rondonia","Roraima","Tocantins"]
data=[]
n = len(states)
for i in range(n):
    data.append(def_amazon_data[states[i]].sum())

avg = sum(data)/n
colors = []
for i in range(n):
  if data[i]>avg:
    colors.append('crimson')
  else:
    colors.append('lightslategray')

fig = go.Figure(data=[go.Bar(x=states, y=data, text=data, textposition='auto', marker_color=colors)])
fig.update_layout(title_text='Total Deforested Area by State')

fig.show()

"""Here we see that the above average amount of deforestation has occured in three states mainly over the period of 15 years."""

fig = make_subplots(rows=3, cols=3, subplot_titles=(states))

for i in range(len(states)):
    fig.add_trace(go.Scatter(x=def_amazon_data['Year'], y=def_amazon_data[states[i]], name = states[i]), row=i//3+1, col=i%3+1)

fig.update_layout(height=800)
fig.update_xaxes(tickmode='linear')
fig.show(config={"displayModeBar": False, "showTips": False})

"""Here we see the deforestation trends over the last 15 years. The three states that have the highest amount of deforestation trend show that this has not occured in recent times but two out of the three states (Rondonia and Para) still show an increasing trend in the line. These are alarms that are to be taken in consideration to avoid further damage. Moreover areas such as Roraima, Acre and Amazonas might not have the highest amount of deforestation lands but they show and alarming increase."""

fig = px.bar(def_amazon_data, x="Year", y=states)
fig.update_layout(title_text='Total Deforested Area per Year', barmode='group', legend_title_text='States')
fig.update_xaxes(tickmode='linear')
fig.show()

"""We see that Para has the highest deforestation occuring over the year. We also see that Mato Grosso still has a high share in cumulative deforestation but majority of that is contributed by the year 2004 and 2005."""

trace1 = go.Bar(x = def_amazon_data['Year'], y=def_amazon_data['Mato Grosso'], name = "Mato Grosso")
trace2 = go.Bar(x = def_amazon_data['Year'], y=def_amazon_data['Para'], name = "Para")
trace3 = go.Bar(x = def_amazon_data['Year'], y=def_amazon_data['Rondonia'], name = "Rondonia")

data = [trace1, trace2, trace3]
layout = go.Layout(barmode = 'group')
fig = go.Figure(data = data, layout = layout)
fig.update_xaxes(tickmode='linear')
iplot(fig)

"""Here we can look closely into the deforestation trend of the lands with highes areas of deforestation."""

states=["Acre","Amazonas","Amapa","Maranhao","Mato Grosso","Para","Rondonia","Roraima","Tocantins","Total"]
data=[]

for i in range(len(states)):
    data.append(go.Scatter(
                    x = def_amazon_data["Year"],
                    y = def_amazon_data[states[i]],
                    mode = "lines+markers",
                    name = states[i]))

layout = go.Layout(title = "Deforestation area (km²)",
                   xaxis = {'title':'Year', 'range':[2004, 2019],},
                   yaxis = {'title':'Value'})

fig = go.Figure(data = data, layout = layout)

iplot(fig)

"""When we compare the trend lines of all the states together we notice that 2008, 2016 and 2019 are time points where deforestation peaked, thus creating an alarm since one of the time points is very recent."""

states=["Acre","Amazonas","Amapa","Maranhao","Mato Grosso","Para","Rondonia","Roraima","Tocantins","Total"]
color_scale=["Viridis","Cividis","Inferno","Hot", "Magma", "Plasma", "Turbo", "Electric", "Blues_r", "RdBu_r", "Thermal", "Aggrnyl", "Haline"]

fig = px.imshow(def_amazon_data[states], x=states, y=list(def_amazon_data["Year"]),
                labels=dict(x="State", y="Year", color="Total"), color_continuous_scale=color_scale[9])
fig.update_yaxes(tickmode='linear')
fig.show()

"""The above heatmap also shows the trend of deforestation confirming to our previous analysis.

# Conclusion
From the following analysis we can conclude that the areas that require conservation are Para, Mato Grosso and Rondonia.
"""